from __future__ import annotations

from copy import deepcopy
from typing import Any

from services.rule_engine import (
    SUPPORTED_METRICS,
    VALID_OPERATORS,
    VALID_RISK_LEVELS,
    VALID_RULE_TYPES,
    VALID_STRATEGY_TYPES,
    get_rule_versions,
    list_rules,
    validate_rule,
)

RULE_SCHEMA_VERSION = "rev26.rule-schema.v2"

CANONICAL_SCHEMAS = {
    "filter": {
        "required": ["type", "id", "name", "version", "enabled", "conditions"],
        "recommended": ["description", "risk_level", "min_score", "compatible_strategy_types", "required_metrics", "avoid_conditions", "score_rules", "metadata"],
        "forbidden": ["entry_rules", "exit_rules", "strategy_type"],
        "sections": ["conditions", "avoid_conditions", "score_rules"],
    },
    "strategy": {
        "required": ["type", "id", "name", "version", "enabled"],
        "recommended": ["description", "risk_level", "strategy_type", "required_metrics", "conditions", "avoid_conditions", "entry_rules", "exit_rules", "metadata"],
        "forbidden": ["min_score", "compatible_strategy_types", "score_rules"],
        "sections": ["conditions", "avoid_conditions", "entry_rules", "exit_rules"],
    },
}


def _issue(level: str, path: str, message: str, code: str) -> dict:
    return {"level": level, "path": path, "message": message, "code": code}


def _unknown_keys(rule: dict, allowed: set[str]) -> list[str]:
    return sorted([key for key in rule.keys() if key not in allowed])


def build_rule_schema_contract() -> dict:
    return {
        "status": "ok",
        "schema_version": RULE_SCHEMA_VERSION,
        "types": sorted(VALID_RULE_TYPES),
        "operators": sorted(VALID_OPERATORS),
        "metrics_count": len(SUPPORTED_METRICS),
        "risk_levels": sorted(VALID_RISK_LEVELS),
        "strategy_types": sorted(VALID_STRATEGY_TYPES),
        "schemas": CANONICAL_SCHEMAS,
        "save_policy": {
            "id": "required_or_autogenerated",
            "type": "locked_by_editor_tab",
            "version": "auto_increment_on_update",
            "snapshot": "required_for_paper_lab_and_reports",
            "restore": "restore_creates_new_version",
        },
    }




def _is_bool(value) -> bool:
    return isinstance(value, bool)


def _looks_like_rule_id(value: str) -> bool:
    text = str(value or "")
    return bool(text) and text.upper() == text and all(ch.isalnum() or ch == "_" for ch in text)


def _danger_warnings(rule: dict) -> list[dict]:
    warnings = []
    rule_type = rule.get("type")
    conditions = rule.get("conditions") or []
    avoid_conditions = rule.get("avoid_conditions") or []
    if rule_type == "filter":
        try:
            if float(rule.get("min_score", 65)) < 50:
                warnings.append(_issue("warning", "min_score", "min_score 50 altı; düşük kaliteli coinleri fazla kabul edebilir.", "LOW_MIN_SCORE"))
        except Exception:
            pass
        if not avoid_conditions:
            warnings.append(_issue("warning", "avoid_conditions", "Filter avoid_conditions boş; spread/volatilite riskleri kaçabilir.", "NO_AVOID_CONDITIONS"))
    if rule_type == "strategy":
        if not rule.get("entry_rules") and not conditions:
            warnings.append(_issue("warning", "entry_rules", "Strategy entry koşulları çok gevşek görünüyor.", "WEAK_ENTRY_RULES"))
        if not rule.get("exit_rules"):
            warnings.append(_issue("warning", "exit_rules", "Strategy exit_rules boş; Paper Lab çıkış davranışı riskli olabilir.", "NO_EXIT_RULES"))
    if not conditions:
        warnings.append(_issue("warning", "conditions", "conditions boş; rule beklenenden geniş çalışabilir.", "NO_CONDITIONS"))
    if rule.get("risk_level") == "high":
        warnings.append(_issue("warning", "risk_level", "High risk rule sadece Paper Lab ve manuel onaylı akışlarda kullanılmalı.", "HIGH_RISK_RULE"))
    return warnings

def validate_rule_schema(rule: dict | None) -> dict:
    base = validate_rule(rule or {})
    errors = list(base.get("errors", []))
    warnings = list(base.get("warnings", []))
    notices: list[dict[str, Any]] = []

    if not isinstance(rule, dict):
        return {"valid": False, "schema_version": RULE_SCHEMA_VERSION, "errors": errors, "warnings": warnings, "notices": notices}

    rule_type = rule.get("type")
    schema = CANONICAL_SCHEMAS.get(rule_type)
    if not schema:
        return {"valid": False, "schema_version": RULE_SCHEMA_VERSION, "errors": errors, "warnings": warnings, "notices": notices}

    for key in schema["required"]:
        if key not in rule or rule.get(key) in (None, ""):
            errors.append(_issue("error", key, f"{key} zorunlu alan.", "REQUIRED_FIELD"))

    if "id" in rule and rule.get("id") and not _looks_like_rule_id(str(rule.get("id"))):
        warnings.append(_issue("warning", "id", "id büyük harf, sayı ve _ formatında normalize edilecek.", "NON_CANONICAL_ID"))

    if "enabled" in rule and not _is_bool(rule.get("enabled")):
        errors.append(_issue("error", "enabled", "enabled boolean olmalı.", "ENABLED_NOT_BOOL"))

    if "metadata" in rule and not isinstance(rule.get("metadata"), dict):
        errors.append(_issue("error", "metadata", "metadata object olmalı.", "METADATA_NOT_OBJECT"))

    try:
        if int(rule.get("version", 1)) < 1:
            errors.append(_issue("error", "version", "version 1 veya daha büyük olmalı.", "VERSION_RANGE"))
    except Exception:
        errors.append(_issue("error", "version", "version sayı olmalı.", "VERSION_NOT_NUMBER"))

    for key in schema["forbidden"]:
        if key in rule:
            errors.append(_issue("error", key, f"{rule_type} rule içinde {key} kullanılmaz.", "FORBIDDEN_FIELD"))

    allowed = set(schema["required"] + schema["recommended"] + ["created_at", "updated_at", "restored_at", "archived_at"])
    unknown = _unknown_keys(rule, allowed)
    for key in unknown:
        warnings.append(_issue("warning", key, "Şema dışı alan. Kritik değilse metadata içine taşı.", "UNKNOWN_FIELD"))

    for section in schema["sections"]:
        value = rule.get(section, [])
        if value is None:
            continue
        if not isinstance(value, list):
            errors.append(_issue("error", section, "Bu alan liste olmalı.", "SECTION_NOT_LIST"))
            continue
        for index, condition in enumerate(value):
            if not isinstance(condition, dict):
                errors.append(_issue("error", f"{section}[{index}]", "Kural satırı object olmalı.", "CONDITION_NOT_OBJECT"))
                continue
            metric = condition.get("metric")
            if metric and metric not in SUPPORTED_METRICS:
                errors.append(_issue("error", f"{section}[{index}].metric", f"Desteklenmeyen metric: {metric}", "UNSUPPORTED_METRIC"))
            operator = condition.get("operator")
            if operator and operator not in VALID_OPERATORS:
                errors.append(_issue("error", f"{section}[{index}].operator", f"Desteklenmeyen operator: {operator}", "UNSUPPORTED_OPERATOR"))

    if rule_type == "strategy" and not (rule.get("conditions") or rule.get("entry_rules")):
        warnings.append(_issue("warning", "conditions", "Stratejide conditions veya entry_rules yok; sinyal çok gevşek kalabilir.", "LOOSE_STRATEGY"))
    if rule_type == "filter" and not rule.get("conditions"):
        warnings.append(_issue("warning", "conditions", "Filtre conditions içermiyor; çok fazla coin geçebilir.", "LOOSE_FILTER"))

    warnings.extend(_danger_warnings(rule))

    return {
        "valid": len(errors) == 0,
        "schema_version": RULE_SCHEMA_VERSION,
        "type": rule_type,
        "errors": errors,
        "warnings": warnings,
        "notices": notices,
        "summary": {
            "error_count": len(errors),
            "warning_count": len(warnings),
            "unknown_fields": unknown,
            "sections_checked": schema["sections"],
        },
    }


def diff_rules(before: dict | None, after: dict | None, prefix: str = "") -> list[dict]:
    before = before or {}
    after = after or {}
    changes = []
    keys = sorted(set(before.keys()) | set(after.keys()))
    for key in keys:
        path = f"{prefix}.{key}" if prefix else key
        if key not in before:
            changes.append({"path": path, "change": "added", "before": None, "after": after.get(key)})
            continue
        if key not in after:
            changes.append({"path": path, "change": "removed", "before": before.get(key), "after": None})
            continue
        left = before.get(key)
        right = after.get(key)
        if isinstance(left, dict) and isinstance(right, dict):
            changes.extend(diff_rules(left, right, path))
        elif left != right:
            changes.append({"path": path, "change": "modified", "before": left, "after": right})
    return changes


def build_rule_diff(username: str, rule_id: str, candidate: dict | None = None) -> dict:
    payload = list_rules(username)
    current = next((item for item in payload.get("rules", []) if item.get("id") == rule_id), None)
    if candidate is None:
        versions = get_rule_versions(username, rule_id).get("versions", [])
        candidate = versions[-1] if versions else None
    return {
        "status": "ok",
        "rule_id": rule_id,
        "current": current,
        "candidate": candidate,
        "diff": diff_rules(current, candidate),
        "change_count": len(diff_rules(current, candidate)),
    }


def build_rule_governance_report(username: str) -> dict:
    payload = list_rules(username)
    rules = payload.get("rules", []) or []
    filters = [r for r in rules if r.get("type") == "filter"]
    strategies = [r for r in rules if r.get("type") == "strategy"]
    validations = [validate_rule_schema(r) for r in rules]
    invalid = [item for item, validation in zip(rules, validations) if not validation.get("valid")]
    warnings = sum(len(v.get("warnings", [])) for v in validations)
    versioned = 0
    version_state = {}
    for rule in rules:
        rule_id = rule.get("id")
        versions = get_rule_versions(username, rule_id).get("versions", []) if rule_id else []
        if versions:
            versioned += 1
        version_state[rule_id] = len(versions)
    return {
        "status": "ok" if not invalid else "review",
        "schema_version": RULE_SCHEMA_VERSION,
        "rule_count": len(rules),
        "filter_count": len(filters),
        "strategy_count": len(strategies),
        "invalid_count": len(invalid),
        "warning_count": warnings,
        "versioned_rules": versioned,
        "version_coverage_pct": round((versioned / len(rules)) * 100, 2) if rules else 0,
        "selected_filter_count": len(payload.get("selected_filter_ids", []) or []),
        "selected_strategy_count": len(payload.get("selected_strategy_ids", []) or []),
        "checks": [
            {"name": "schema_contract", "status": "ok", "detail": RULE_SCHEMA_VERSION},
            {"name": "filter_strategy_separation", "status": "ok" if all(r.get("type") in VALID_RULE_TYPES for r in rules) else "blocked"},
            {"name": "valid_rules", "status": "ok" if not invalid else "review", "detail": len(invalid)},
            {"name": "version_history", "status": "ok" if versioned or not rules else "review", "detail": version_state},
            {"name": "paper_lab_selection", "status": "ok" if payload.get("selected_filter_ids") or payload.get("selected_strategy_ids") else "review"},
        ],
        "invalid_rules": [{"id": r.get("id"), "name": r.get("name"), "type": r.get("type")} for r in invalid],
        "version_state": version_state,
    }
